package com.fly.run.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by kongwei on 2017/3/10.
 */

public class CircleBean implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.nearby
     *
     * @mbg.generated
     */
    private String nearby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.continue_days
     *
     * @mbg.generated
     */
    private Integer continueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.distance
     *
     * @mbg.generated
     */
    private Long distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.speed
     *
     * @mbg.generated
     */
    private Double speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.use_time
     *
     * @mbg.generated
     */
    private String useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.heat
     *
     * @mbg.generated
     */
    private String heat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column run.coordinate_list
     *
     * @mbg.generated
     */
    private String coordinateList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table run
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.id
     *
     * @return the value of run.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.id
     *
     * @param id the value for run.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.account_id
     *
     * @return the value of run.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.account_id
     *
     * @param accountId the value for run.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.longitude
     *
     * @return the value of run.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.longitude
     *
     * @param longitude the value for run.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.latitude
     *
     * @return the value of run.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.latitude
     *
     * @param latitude the value for run.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.address
     *
     * @return the value of run.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.address
     *
     * @param address the value for run.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.nearby
     *
     * @return the value of run.nearby
     *
     * @mbg.generated
     */
    public String getNearby() {
        return nearby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.nearby
     *
     * @param nearby the value for run.nearby
     *
     * @mbg.generated
     */
    public void setNearby(String nearby) {
        this.nearby = nearby == null ? null : nearby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.continue_days
     *
     * @return the value of run.continue_days
     *
     * @mbg.generated
     */
    public Integer getContinueDays() {
        return continueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.continue_days
     *
     * @param continueDays the value for run.continue_days
     *
     * @mbg.generated
     */
    public void setContinueDays(Integer continueDays) {
        this.continueDays = continueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.distance
     *
     * @return the value of run.distance
     *
     * @mbg.generated
     */
    public Long getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.distance
     *
     * @param distance the value for run.distance
     *
     * @mbg.generated
     */
    public void setDistance(Long distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.speed
     *
     * @return the value of run.speed
     *
     * @mbg.generated
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.speed
     *
     * @param speed the value for run.speed
     *
     * @mbg.generated
     */
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.use_time
     *
     * @return the value of run.use_time
     *
     * @mbg.generated
     */
    public String getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.use_time
     *
     * @param useTime the value for run.use_time
     *
     * @mbg.generated
     */
    public void setUseTime(String useTime) {
        this.useTime = useTime == null ? null : useTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.heat
     *
     * @return the value of run.heat
     *
     * @mbg.generated
     */
    public String getHeat() {
        return heat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.heat
     *
     * @param heat the value for run.heat
     *
     * @mbg.generated
     */
    public void setHeat(String heat) {
        this.heat = heat == null ? null : heat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.cover
     *
     * @return the value of run.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.cover
     *
     * @param cover the value for run.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.city
     *
     * @return the value of run.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.city
     *
     * @param city the value for run.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.district
     *
     * @return the value of run.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.district
     *
     * @param district the value for run.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.create_at
     *
     * @return the value of run.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.create_at
     *
     * @param createAt the value for run.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column run.coordinate_list
     *
     * @return the value of run.coordinate_list
     *
     * @mbg.generated
     */
    public String getCoordinateList() {
        return coordinateList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column run.coordinate_list
     *
     * @param coordinateList the value for run.coordinate_list
     *
     * @mbg.generated
     */
    public void setCoordinateList(String coordinateList) {
        this.coordinateList = coordinateList == null ? null : coordinateList.trim();
    }
}
