package com.fly.run.bean;

import java.io.Serializable;
import java.util.Date;

public class CircleBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.account_id
     *
     * @mbg.generated
     */
//    private Integer account_id;
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.photos
     *
     * @mbg.generated
     */
    private String photos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.thumbs
     *
     * @mbg.generated
     */
    private String thumbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.create_time
     *
     * @mbg.generated
     */
//    private Date create_time;
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.modify_time
     *
     * @mbg.generated
     */
//    private Date modify_time;
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.run_id
     *
     * @mbg.generated
     */
    private Integer runId;

    private String name;

    private String reply;
    private int replyCount;
    private int likeCount;
    private int shareCount;
    private boolean hasThisUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.id
     *
     * @return the value of circle.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.id
     *
     * @param id the value for circle.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.description
     *
     * @return the value of circle.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.description
     *
     * @param description the value for circle.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.account
     *
     * @return the value of circle.account
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.account
     *
     * @param account the value for circle.account
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.account_id
     *
     * @return the value of circle.account_id
     * @mbg.generated
     */
//    public Integer getAccountId() {
//        return account_id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column circle.account_id
//     *
//     * @param accountId the value for circle.account_id
//     * @mbg.generated
//     */
//    public void setAccountId(Integer accountId) {
//        this.account_id = accountId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.photos
     *
     * @return the value of circle.photos
     * @mbg.generated
     */
    public String getPhotos() {
        return photos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.photos
     *
     * @param photos the value for circle.photos
     * @mbg.generated
     */
    public void setPhotos(String photos) {
        this.photos = photos == null ? null : photos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.thumbs
     *
     * @return the value of circle.thumbs
     *
     * @mbg.generated
     */
    public String getThumbs() {
        return thumbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.thumbs
     *
     * @param thumbs the value for circle.thumbs
     *
     * @mbg.generated
     */
    public void setThumbs(String thumbs) {
        this.thumbs = thumbs == null ? null : thumbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.create_time
     *
     * @return the value of circle.create_time
     * @mbg.generated
     */
//    public Date getCreateTime() {
//        return create_time;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column circle.create_time
//     *
//     * @param createTime the value for circle.create_time
//     * @mbg.generated
//     */
//    public void setCreateTime(Date createTime) {
//        this.create_time = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column circle.modify_time
//     *
//     * @return the value of circle.modify_time
//     * @mbg.generated
//     */
//    public Date getModify_time() {
//        return modify_time;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column circle.modify_time
//     *
//     * @param modifyTime the value for circle.modify_time
//     * @mbg.generated
//     */
//    public void setModify_time(Date modifyTime) {
//        this.modify_time = modifyTime;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.address
     *
     * @return the value of circle.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.address
     *
     * @param address the value for circle.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.run_id
     *
     * @return the value of circle.run_id
     * @mbg.generated
     */
    public Integer getRunId() {
        return runId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.run_id
     *
     * @param runId the value for circle.run_id
     * @mbg.generated
     */
    public void setRunId(Integer runId) {
        this.runId = runId;
    }

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer account_id) {
        this.accountId = account_id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date create_time) {
        this.createTime = create_time;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public CircleBean setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
        return this;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getReply() {
        return reply;
    }

    public void setReply(String reply) {
        this.reply = reply;
    }

    public int getReplyCount() {
        return replyCount;
    }

    public void setReplyCount(int replyCount) {
        this.replyCount = replyCount;
    }

    public int getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(int likeCount) {
        this.likeCount = likeCount;
    }

    public int getShareCount() {
        return shareCount;
    }

    public void setShareCount(int shareCount) {
        this.shareCount = shareCount;
    }

    public boolean isHasThisUser() {
        return hasThisUser;
    }

    public void setHasThisUser(boolean hasThisUser) {
        this.hasThisUser = hasThisUser;
    }
}