package com.fly.run.bean;

import java.io.Serializable;
import java.util.Date;

public class CircleReply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_circle_id
     *
     * @mbg.generated
     */
    private Integer replyCircleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_user_id
     *
     * @mbg.generated
     */
    private Integer replyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_user_name
     *
     * @mbg.generated
     */
    private String replyUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_time
     *
     * @mbg.generated
     */
    private Date replyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_id
     *
     * @mbg.generated
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circlereply.reply_root_id
     *
     * @mbg.generated
     */
    private Integer replyRootId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circlereply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.id
     *
     * @return the value of circlereply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.id
     *
     * @param id the value for circlereply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_circle_id
     *
     * @return the value of circlereply.reply_circle_id
     *
     * @mbg.generated
     */
    public Integer getReplyCircleId() {
        return replyCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_circle_id
     *
     * @param replyCircleId the value for circlereply.reply_circle_id
     *
     * @mbg.generated
     */
    public void setReplyCircleId(Integer replyCircleId) {
        this.replyCircleId = replyCircleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_user_id
     *
     * @return the value of circlereply.reply_user_id
     *
     * @mbg.generated
     */
    public Integer getReplyUserId() {
        return replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_user_id
     *
     * @param replyUserId the value for circlereply.reply_user_id
     *
     * @mbg.generated
     */
    public void setReplyUserId(Integer replyUserId) {
        this.replyUserId = replyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_user_name
     *
     * @return the value of circlereply.reply_user_name
     *
     * @mbg.generated
     */
    public String getReplyUserName() {
        return replyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_user_name
     *
     * @param replyUserName the value for circlereply.reply_user_name
     *
     * @mbg.generated
     */
    public void setReplyUserName(String replyUserName) {
        this.replyUserName = replyUserName == null ? null : replyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_content
     *
     * @return the value of circlereply.reply_content
     *
     * @mbg.generated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_content
     *
     * @param replyContent the value for circlereply.reply_content
     *
     * @mbg.generated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_time
     *
     * @return the value of circlereply.reply_time
     *
     * @mbg.generated
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_time
     *
     * @param replyTime the value for circlereply.reply_time
     *
     * @mbg.generated
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_id
     *
     * @return the value of circlereply.reply_id
     *
     * @mbg.generated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_id
     *
     * @param replyId the value for circlereply.reply_id
     *
     * @mbg.generated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circlereply.reply_root_id
     *
     * @return the value of circlereply.reply_root_id
     *
     * @mbg.generated
     */
    public Integer getReplyRootId() {
        return replyRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circlereply.reply_root_id
     *
     * @param replyRootId the value for circlereply.reply_root_id
     *
     * @mbg.generated
     */
    public void setReplyRootId(Integer replyRootId) {
        this.replyRootId = replyRootId;
    }
}